%%Definingstruct
Members=struct('Name',{},'HomeDistrict',{},'Age',{},'Course',{},'Village',{},'Tribe',{},'Religion',{},'Interest',{},'FacialRepresentation',{});
%Member1
Members(1).Name='KemigisaTasha';
Members(1).HomeDistrict='Kampala';
Members(1).Age=19;
Members(1).Course='AMI';
Members(1).Village='Kololo';
Members(1).Tribe='Mutooro';
Members(1).Religion='Christian';
Members(1).Interest='shopping';
Members(1).FacialRepresentation=imread("ngc6543a.jpg");
%Member2
Members(2).Name='AyebarePrudence';
Members(2).HomeDistrict='Mbarara';
Members(2).Age=22;
Members(2).Course='WAR';
Members(2).Village='Mbarara';
Members(2).Tribe='Munyankore';
Members(2).Religion='Christian';
Members(2).Interest='Eating';
Members(2).FacialRepresentation=imread("ngc6543a.jpg");
%Member3
Members(3).Name='LUCKYDOROTHY';
Members(3).HomeDistrict='Isingiro';
Members(3).Age=21;
Members(3).Course='MEB';
Members(3).Village='Isingiro';
Members(3).Tribe='Muganda';
Members(3).Religion='Christian';
Members(3).Interest='Eating';
Members(3).FacialRepresentation=imread("ngc6543a.jpg");
%Member4
Members(4).Name='Kisakyepriscilapatience';
Members(4).HomeDistrict='bugiri';
Members(4).Age=21;
Members(4).Course='war';
Members(4).Village='nkusi';
Members(4).Tribe='musoga';
Members(4).Religion='Christian';
Members(4).Interest='reading';
Members(4).FacialRepresentation=imread("ngc6543a.jpg");
%member5
Members(5).Name='Kenyimoses';
Members(5).HomeDistrict='jinja';
Members(5).Age=21;
Members(5).Course='meb';
Members(5).Village='buwenda';
Members(5).Tribe='kuku';
Members(5).Religion='Christian';
Members(5).Interest='swimming';
Members(5).FacialRepresentation=imread("ngc6543a.jpg");
%member6
Members(6).Name='muwazadeogratius';
Members(6).HomeDistrict='jinja';
Members(6).Age=21;
Members(6).Course='pti';
Members(6).Village='masaka';
Members(6).Tribe='muganda';
Members(6).Religion='Christian';
Members(6).Interest='sleeping';
Members(6).FacialRepresentation=imread("ngc6543a.jpg");
%member7
Members(7).Name='zzimbeenock';
Members(7).HomeDistrict='zana';
Members(7).Age=21;
Members(7).Course='war';
Members(7).Village='masaka';
Members(7).Tribe='muganda';
Members(7).Religion='Christian';
Members(7).Interest='rapping';
Members(7).FacialRepresentation=imread("ngc6543a.jpg");
%Member(8)
Members(8).Name='opiosamodwori';
Members(8).HomeDistrict='mbale';
Members(8).Age=22;
Members(8).Course='war';
Members(8).Village='mutoto';
Members(8).Tribe='samia';
Members(8).Religion='Christian';
Members(8).Interest='football';
Members(8).FacialRepresentation=imread("ngc6543a.jpg");
%Member(9)
Members(9).Name='oketchsimon';
Members(9).HomeDistrict='jinja';
Members(9).Age=22;
Members(9).Course='ami';
Members(9).Village='kigaya';
Members(9).Tribe='musoga';
Members(9).Religion='Christian';
Members(9).Interest='football';
Members(9).FacialRepresentation=imread("ngc6543a.jpg");
%Member10
Members(10).Name='NamanyaPrecious';
Members(10).HomeDistrict='wakiso';
Members(10).Age=21;
Members(10).Course='ami';
Members(10).Village='bukemba';
Members(10).Tribe='munyankole';
Members(10).Religion='Christian';
Members(10).Interest='reading';
Members(10).FacialRepresentation=imread("ngc6543a.jpg");
%Member11
Members(11).Name='NakyagabaBabra';
Members(11).HomeDistrict='busia';
Members(11).Age=23;
Members(11).Course='ape';
Members(11).Village='buhayenji';
Members(11).Tribe='samia';
Members(11).Religion='Christian';
Members(11).Interest='watching';
Members(11).FacialRepresentation=imread("ngc6543a.jpg");
%Member12
Members(12).Name='PearlFlavia';
Members(12).HomeDistrict='kazo';
Members(12).Age=22;
Members(12).Course='war';
Members(12).Village='kashwa';
Members(12).Tribe='munyankole';
Members(12).Religion='Christian';
Members(12).Interest='playingvolleyball';
Members(12).FacialRepresentation=imread("ngc6543a.jpg");
%Member13
Members(13).Name='JoanRachaelLagu';
Members(13).HomeDistrict='Arua';
Members(13).Age=21;
Members(13).Course='war';
Members(13).Village='Ediofe';
Members(13).Tribe='Madi';
Members(13).Religion='Christian';
Members(13).Interest='Reading';
Members(13).FacialRepresentation=imread("ngc6543a.jpg");
%Member14
Members(14).Name='KagoyaAnnLauriene';
Members(14).HomeDistrict='Iganga';
Members(14).Age=21;
Members(14).Course='PTI';
Members(14).Village='Iganga';
Members(14).Tribe='MUsoga';
Members(14).Religion='Christian';
Members(14).Interest='WatchingMovies';
Members(14).FacialRepresentation=imread("ngc6543a.jpg");
%Member15
Members(15).Name='OyugiAndrewLinus';
Members(15).HomeDistrict='Kaberamaido';
Members(15).Age=23;
Members(15).Course='WAR';
Members(15).Village='Okile';
Members(15).Tribe='Kumam';
Members(15).Religion='Christian';
Members(15).Interest='WatchingMovies';
Members(15).FacialRepresentation=imread("ngc6543a.jpg");
%Member16
Members(16).Name='BangiRehemaFaridah';
Members(16).HomeDistrict='Kaliro';
Members(16).Age=22;
Members(16).Course='AMI';
Members(16).Village='Kaliro';
Members(16).Tribe='Musoga';
Members(16).Religion='Muslim';
Members(16).Interest='WatchingMovies';
Members(16).FacialRepresentation=imread("ngc6543a.jpg");
%Member17
Members(17).Name='NangoliDerick';
Members(17).HomeDistrict='Bulambuli';
Members(17).Age=22;
Members(17).Course='AMI';
Members(17).Village='SamazuTCB';
Members(17).Tribe='Gishu';
Members(17).Religion='Christian';
Members(17).Interest='FootBall';
Members(17).FacialRepresentation=imread("ngc6543a.jpg");